models/alert.py
from dataclasses import dataclass, field
from typing import List, Dict
import uuid
from libs.mailgun import Mailgun
from common.database import Database
from models.item import Item
from models.user import User
from models.model import Model


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "price_limit": self.price_limit,
            "item_id": self.item._id,
            "user_email": self.user_email,
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        if self.item.price < self.price_limit:
            print(
                f"Item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}."
            )
            Mailgun.send_email(
                email=[self.user_email],
                subject=f"Notification for {self.name}",
                text=f"Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.",
                html=f'<p>Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}. Check your item out <a href="{self.item.url}>here</a>.</p>',
            )

views/alerts.py
import json
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.store import Store
from models.item import Item
from models.user import requires_login

alert_blueprint = Blueprint("alerts", __name__)


@alert_blueprint.route("/")
@requires_login
def index():
    alerts = Alert.find_many_by("user_email", session["email"])
    return render_template("alerts/index.html", alerts=alerts)


@alert_blueprint.route("/new", methods=["GET", "POST"])
@requires_login
def create_alert():
    if request.method == "POST":
        item_url = request.form["item_url"]

        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_mongo()

        alert_name = request.form["name"]
        price_limit = float(request.form["price_limit"])

        Alert(alert_name, item._id, price_limit, session["email"]).save_to_mongo()

    # What happens if it's a GET request
    return render_template("alerts/new_alert.html")


@alert_blueprint.route("/edit/<string:alert_id>", methods=["GET", "POST"])
@requires_login
def edit_alert(alert_id):
    if request.method == "POST":
        price_limit = float(request.form["price_limit"])

        alert = Alert.get_by_id(alert_id)
        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for(".index"))

    # What happens if it's a GET request
    return render_template("alerts/edit_alert.html", alert=Alert.get_by_id(alert_id))


@alert_blueprint.route("/delete/<string:alert_id>")
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session["email"]:
        alert.remove_from_mongo()
    return redirect(url_for(".index"))

templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Edit Alert</h1>
</header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ alert.item.name }}" disabled>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="120"
            value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Alerts</h1>
</header>
<section>
    <div class="list-group">
        {% for alert in alerts %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">{{ alert.name }}</h4>
            <p>
                <a href="{{ alert.item.url }}">{{ alert.item.url }}</a> (last price £{{ alert.item.price }})
            </p>
            <a class="btn btn-secondary" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">
                Edit
            </a>
            <a class="btn btn-danger mt-3" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">
                Permanently Delete Alert
            </a>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary mt-3" href="{{ url_for('alerts.create_alert') }}">
        Create new
    </a>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Create Alert</h1>
</header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Surface Pro 6">
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url" placeholder="https://..."
                aria-describedby="itemURLHelp">
            <small id="itemURLHelp" class="form-text text-muted">
                What is the URL of the element you wish to make an alert for?
            </small>
        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="120"
                aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                Under which price for the item would you like to get notified?
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</section>
{% endblock %}