models/store.py
from dataclasses import dataclass, field
import uuid
import re
from typing import Dict
from models.model import Model
from common.database import Database


@dataclass(eq=False)
class Store(Model):
    collection: str = field(init=False, default="stores")
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, store_name: str) -> "Store":
        return cls.find_one_by("name", store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> "Store":
        url_regex = {"$regex": '^{}'.format(url_prefix)}
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def find_by_url(cls, url: str) -> "Store":
        """
        Return a store from a url like "http://www.johnlewis.com/item/sdfj4h5g4g21k.html"
        :param url: The item's URL
        :return: a Store
        """
        pattern = re.compile(r"(https?:\/\/.*?\/)")
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/stores.py
import json
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store
from models.user import requires_admin

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

    # What happens if it's a GET request
    return render_template("stores/new_store.html")



@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    # What happens if it's a GET request
    return render_template("stores/edit_store.html", store=Store.get_by_id(store_id))


@store_blueprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Edit Store</h1>
</header>
<section class="create-store-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="John Lewis" value="{{ store.name }}">
        </div>
        <div class="form-group">
            <label for="url_prefix">URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..."
                value="{{ store.url_prefix }}" aria-describedby="urlPrefixHelp">
            <small id="urlPrefixHelp" class="form-text text-muted">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span"
                value="{{ store.tag_name }}" aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                What HTML tag contains the price information for items in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}'
                value="{{ store.query }}" aria-describedby="queryHelp">
            <small id="queryHelp" class="form-text text-muted">
                What attributes are on the element that contain the price? This is so we can find it on the page.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Create Store</h1>
</header>
<section class="create-store-form">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="John Lewis">
        </div>
        <div class="form-group">
            <label for="url_prefix">URL Prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://..."
                aria-describedby="urlPrefixHelp">
            <small id="urlPrefixHelp" class="form-text text-muted">
                What URL will all its items start with?
            </small>
        </div>
        <div class="form-group">
            <label for="tag_name">HTML Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span"
                aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                What HTML tag contains the price information for items in this store?
            </small>
        </div>
        <div class="form-group">
            <label for="query">HTML Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}'
                aria-describedby="queryHelp">
            <small id="queryHelp" class="form-text text-muted">
                What attributes are on the element that contain the price? This is so we can find it on the page.
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</section>
{% endblock %}

templates/stores/store_index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Stores</h1>
</header>
<section>
    <div class="list-group">
        {% for store in stores %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">{{ store.name }}</h4>
            <p>
                For URLs starting with {{ store.url_prefix }}.
            </p>
            {% if session['email'] == config.ADMIN %}
            <a class="btn btn-secondary" href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                Edit
            </a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">
                Permanently Delete Store
            </a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% if session['email'] == config.ADMIN %}
    <a class="btn btn-primary mt-3" href="{{ url_for('stores.create_store') }}">
        Create new
    </a>
    {% endif %}
</section>
{% endblock %}